### ISSUE TITLE
Signature Auth flow isn't working under new TLS 1.2 SSL code

### ISSUE THREAD

**Issue by devondragon** [sparkred-insight/PayPalModule#2]
PayPal recommends using the Cert based auth mechanism, which is working correctly in the new modules, under TLS 1.2.  However there is a known issue if you are using the less-secure Signature based auth, and the new TLS 1.2 modules.

```
10:18:08,554 ERROR [nucleusNamespace.sparkred.paypal.PayPalProcessor] (http-/10.40.189.182:10180-9) PayPalProcessor.callSetExpressCheckoutDetailedResponse: caught IOException during callReceived fatal alert: handshake_failure: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) [jsse.jar:1.7.0_65]
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) [jsse.jar:1.7.0_65]
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1959) [jsse.jar:1.7.0_65]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1077) [jsse.jar:1.7.0_65]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312) [jsse.jar:1.7.0_65]
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:702) [jsse.jar:1.7.0_65]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122) [jsse.jar:1.7.0_65]
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.flushBuffer(AbstractSessionOutputBuffer.java:147) [_SPARKRED.PayPal_slib_shttpcore-4.2.4.jar:4.2.4]
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:167) [_SPARKRED.PayPal_slib_shttpcore-4.2.4.jar:4.2.4]
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:119) [_SPARKRED.PayPal_slib_shttpcore-4.2.4.jar:4.2.4]
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:126) [_SPARKRED.PayPal_slib_shttpcore-4.2.4.jar:4.2.4]
	at org.apache.http.entity.StringEntity.writeTo(StringEntity.java:176) [_SPARKRED.PayPal_slib_shttpcore-4.2.4.jar:4.2.4]
	at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:98) [_SPARKRED.PayPal_slib_shttpcore-4.2.4.jar:4.2.4]
	at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108) [_SPARKRED.PayPal_slib_shttpclient-4.2.5.jar:4.2.5]
	at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:122) [_SPARKRED.PayPal_slib_shttpcore-4.2.4.jar:4.2.4]
	at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:271) [_SPARKRED.PayPal_slib_shttpcore-4.2.4.jar:4.2.4]
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:197) [_SPARKRED.PayPal_slib_shttpclient-4.2.5.jar:4.2.5]
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:257) [_SPARKRED.PayPal_slib_shttpcore-4.2.4.jar:4.2.4]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) [_SPARKRED.PayPal_slib_shttpcore-4.2.4.jar:4.2.4]
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:715) [_SPARKRED.PayPal_slib_shttpclient-4.2.5.jar:4.2.5]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:520) [_SPARKRED.PayPal_slib_shttpclient-4.2.5.jar:4.2.5]
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906) [_SPARKRED.PayPal_slib_shttpclient-4.2.5.jar:4.2.5]
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:827) [_SPARKRED.PayPal_slib_shttpclient-4.2.5.jar:4.2.5]
	at com.sparkred.paypal.PayPalConnection.call(PayPalConnection.java:302) [_SPARKRED.PayPal_slib_sclasses.jar:]
	at com.sparkred.paypal.PayPalProcessor.callSetExpressCheckoutDetailedResponse(PayPalProcessor.java:726) [_SPARKRED.PayPal_slib_sclasses.jar:]
	at com.sparkred.paypal.PayPalProcessor.callSetExpressCheckout(PayPalProcessor.java:469) [_SPARKRED.PayPal_slib_sclasses.jar:]
	at com.sparkred.paypal.formhandler.CRSPayPalCartFormHandler.handleCheckoutWithPayPal(CRSPayPalCartFormHandler.java:102) [_SPARKRED.PayPal_slib_sclasses.jar:]
```

**Comment by devondragon** [comment]
This is a false alarm cause by a bad branch build config.
